version: '3.3'

services:
  gitlab:
      image: gitlab/gitlab-ce:8.5.8-ce.0
      ports: [ "8180:80", "8122:22" ]
      volumes:
      - gitlab-conf:/etc/gitlab
      - gitlab-log:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
      environment:
      - GITLAB_ROOT_PASSWORD=aqwzsx12341

volumes:
  gitlab-conf:
  gitlab-log:
  gitlab-data:
